V.Petrov, Flow Homework
Otus-Android/HomeWork_03 pull request #101
Opened 2023-01-15 13:18 UTC by flyingV805

2023-01-21 16:25 UTC, antonkazakov requested changes
Привет. Оставил пару комментов

2023-01-21 16:25 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Тебе здесь можно это убрать, подписку сделать в репозитории на эмиты

2023-01-21 16:25 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit(it.toString())
emit(it.toString()) можно вынести чтобы не дублировать

2023-01-22 05:15 UTC, flyingV805 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit(it.toString())
Логично, исправлено!

2023-01-22 05:41 UTC, flyingV805 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Если честно, не вполне понял. Имелось ввиду, пробросить Flow из Repository в View, через ViewModel? Т.е. не создавать новый Flow во ViewModel, и ограничится одним?

2023-01-22 05:46 UTC, flyingV805 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Ааааа, рискну предположить что проблема в коде на строчках 24, 25 а не 20, 21 ? Если так, то исправлено 😅

2023-01-22 09:56 UTC, antonkazakov reviewed
👍

2023-01-22 09:56 UTC, closed without merging