Andrey Bukreev homework Flow
Otus-Android/HomeWork_03 pull request #104
Opened 2023-01-16 12:18 UTC by Andre-nerd

Добрый день Абакар,
Буду признателен за обратную связь.
С уважением,
Андрей

2023-01-21 14:56 UTC, antonkazakov requested changes
Привет. Оставил несколько рекомендаций

2023-01-21 14:56 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(Dispatchers.Main) {
У тебя viewModelScope уже содержит Main в качестве диспатчера, поэтому правильнее убрать withContext, и добавить переключение диспатчера для эмиттера

2023-01-21 14:56 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>                  catsRepository.listenForCatFacts().collect {
Думаю будет правильным еще добавить обработку ошибок через `catch` оператор / `try/catch` блок

2023-01-21 14:56 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +    }.catch { exception ->
Я бы перенес это во Вьюмодель, а так все ок

2023-01-21 14:56 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                sampleRepository.completed()
sampleRepository.completed() вызовется только если упадет исключение

2023-01-23 09:02 UTC, Andre-nerd commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(Dispatchers.Main) {
Исправил

2023-01-23 09:05 UTC, Andre-nerd commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>                  catsRepository.listenForCatFacts().collect {
Исправил

2023-01-23 09:06 UTC, Andre-nerd commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +    }.catch { exception ->
Перенес

2023-01-23 09:10 UTC, Andre-nerd commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                sampleRepository.completed()
Да, точно. Изменил
    fun task4(): Flow<Int> {
        return sampleRepository.produceNumbers()
            .onEach {
                sampleRepository.completed() 
            }
            .catch {throwable ->
                when (throwable) {
                    is IllegalArgumentException -> emit(-1)
                    else -> throw throwable
                }
            }

2023-02-05 06:47 UTC, closed without merging