Homework_02_Flow
Otus-Android/HomeWork_03 pull request #105
Opened 2023-01-21 16:17 UTC by Eugeniydak

2023-01-21 16:23 UTC, Eugeniydak commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> -                    _catsLiveData.value = it
Починка краша была с помощью postValue(), чтобы действие происходило в Main-потоке.

2023-01-22 11:09 UTC, antonkazakov requested changes
Привет. Оставил пару комменатриев

2023-01-22 11:09 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> -                    _catsLiveData.value = it
Я думаю правильнее тебе
1) Перевести коллектор на мейн диспатчер, чтобы можно было обновлять UI
2) Перевести эмиттер на IO

2023-01-22 11:09 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            sampleRepository.completed()
В целом все ок, но имхо можно гораздо компактнее сделать используя 2 оператора
1) catch
2) onCompletion

2023-01-22 11:09 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        launch(job) {
Можно взять lifecycleScope, чтобы вручную не управлять

2023-02-05 06:52 UTC, antonkazakov commented
👍

2023-02-05 06:52 UTC, closed without merging