На проверку
Otus-Android/HomeWork_03 pull request #128
Opened 2023-07-13 11:04 UTC by VirKato-dev

Все тесты проходят

2023-07-15 14:10 UTC, VirKato-dev commented
нужна проверка домашки

2023-07-23 10:30 UTC, antonkazakov requested changes
Привет. Оставил пару комментариев

2023-07-23 10:30 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    // поэтому обработку исключения перенёс в catsRepository
Ну тут момент спорный. Например ты хочешь из-за ошибки полученной при чтении/записи сформировать какую то сущность для отображения пользаку, например, в тосте. И ты получается будешь в репозитории формировать UI сущность?

2023-07-23 10:30 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            .apply { sampleRepository.completed() }
Есть специальный оператор для этого. Сейчас это просто вне флоу вызывается

2023-08-22 07:53 UTC, VirKato-dev commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            .apply { sampleRepository.completed() }
https://github.com/Otus-Android/FlowHomework/pull/128/commits/5cb5bdb48445a7c79ceb6da98e3dafc087a43657

2023-08-22 07:53 UTC, VirKato-dev commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    // поэтому обработку исключения перенёс в catsRepository
https://github.com/Otus-Android/FlowHomework/pull/128/commits/c32fe9e84e45ffcedd60d49728e7c146c908f172

2023-09-17 09:11 UTC, closed without merging