flow homework
Otus-Android/HomeWork_03 pull request #137
Opened 2023-08-06 14:32 UTC by 78trav

2023-08-13 10:27 UTC, antonkazakov requested changes
Привет. Пара комментов

2023-08-13 10:27 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                emit(Success(catsService.getCatFact()))
Вот эти наследники резалта все таки сущность ближе к UI слою, лучше их создавать в ВМ и распаковывать во вью

2023-08-13 10:27 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно убрать, переключить эммитер через оператор

2023-08-13 11:39 UTC, 78trav commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                emit(Success(catsService.getCatFact()))
В задании:
3. В случае если возникнет ошибка в стриме, нужно заэмитить айтем `Result.Error`*

*Создать sealed класс `Result`. Унаследовать от него классы `Success<T>`, `Error`.

Если эмиттить не эти объекты, а допустим просто строки, то как тогда отличить ошибку от нормального результата... Не понимаю :)

2023-08-27 18:39 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                emit(Success(catsService.getCatFact()))
Их нужно эмитить во вьюмодели в стейтфлоу/шередстейтфлоу

2023-08-27 18:39 UTC, antonkazakov requested changes

2023-08-27 18:39 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
Так а зачем его на Io запускать?

2023-09-09 17:39 UTC, closed without merging