Flow Homework - callback to coroutine
Otus-Android/HomeWork_03 pull request #139
Opened 2023-10-12 08:57 UTC by Arthur11232

- fixed crash: Emit doesn't work in background thread
- changed LiveData to StateFlow
- made sealed class Result
- in case error emitted Result.Error

2023-10-30 18:28 UTC, antonkazakov requested changes
Привет. оставил несколько замечаний

2023-10-30 18:28 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                println()
А это зачем?)

2023-10-30 18:28 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsService.kt
> +    suspend fun getCatFact(): Result<Fact>
Не понял, а каким образом у тебя ретрофит+десериализатор тут превратит это в Result?

2023-10-30 18:28 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Fact?>(null)
Оставь один флоу публичный, типизируй его Result<>

2023-10-30 18:28 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(Dispatchers.Main) {
У тебя уже в viewModelScope используется Dispatchers.Main же

2023-10-31 08:37 UTC, Arthur11232 commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                println()
просто забыл удалить )))

2023-12-10 16:58 UTC, closed without merging