Homework03 - Flow Евтушенко Максим
Otus-Android/HomeWork_03 pull request #141
Opened 2023-10-13 16:20 UTC by evtushenko99

1. Поправил ошибку, метод LiveData.setValue можно вызывать только на главном потоке
2. Добавил подписку на stateFlow
3. Создал общий sealedClass Result,который помогает обрабатывать результат в активити
4. Добавил exceptionHandler для отображения ошибки

1. Реализовал методы task1-task4

2023-10-30 18:35 UTC, antonkazakov requested changes
Привет. Пара замечаний

2023-10-30 18:35 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/presentation/CatsViewModel.kt
> +    val catsLiveData: LiveData<Fact> = _catsLiveData
А зачем лайвдата тебе? Оставь один флоу типизированный Result и коллектор на lifecycleScope

2023-10-30 18:35 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            val resultString = StringBuilder("")
А зачем тебе стрингбилдер здесь? ты же можешь просто строки кидать, это оптимальнее решение

2023-11-11 07:41 UTC, evtushenko99 commented on flowcats/src/main/java/otus/homework/flowcats/presentation/CatsViewModel.kt
> +    val catsLiveData: LiveData<Fact> = _catsLiveData
А я ее и не использую,  просто оставил для вида,что есть и такой вариант. Закомментировал строку,где ее использую.

2023-11-11 07:41 UTC, evtushenko99 commented on flowcats/src/main/java/otus/homework/flowcats/presentation/CatsViewModel.kt
> +    val catsLiveData: LiveData<Fact> = _catsLiveData
Удалил неиспользуемый код

2023-11-11 07:46 UTC, evtushenko99 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            val resultString = StringBuilder("")
Чтобы не делать дополнительные проверки на деление на 15. Так у меня две проверки и готова результирующая строка

2023-11-11 07:48 UTC, evtushenko99 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            val resultString = StringBuilder("")
Я поправил решение, оно было не совсем корректное и тесты, но стрингбилдер оставил. Думаю это лучше, чем 3 проверки делать (может не прав)

2023-11-26 12:16 UTC, antonkazakov reviewed
👍

2023-11-26 12:16 UTC, closed without merging