Solution
Otus-Android/HomeWork_03 pull request #143
Opened 2023-10-20 10:26 UTC by andreiRookie

2023-10-30 19:53 UTC, antonkazakov requested changes
Привет, оставил пару замечаний

2023-10-30 19:53 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно убрать, коллектор нужно на main запустить, эмиттер на io(хотя в целом когда ты работаешь с ретрофитом можно не менять диспатчер)

2023-10-30 19:53 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                            emit("$number")
emit("$number") можно вынести из when

2023-10-30 19:53 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            .flowOn(Dispatchers.Default)
Думаю здесь можно не переключать

2023-10-30 19:53 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            .flowOn(Dispatchers.Default)
Тоже можно не переключать

2023-11-01 15:30 UTC, andreiRookie commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
пофиксил

2023-11-01 15:30 UTC, andreiRookie commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                            emit("$number")
сделал

2023-11-01 15:32 UTC, andreiRookie commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            .flowOn(Dispatchers.Default)
убрал

2023-11-01 15:35 UTC, andreiRookie commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            .flowOn(Dispatchers.Default)
тут тож убрал

2023-11-01 15:37 UTC, andreiRookie commented
> Привет, оставил пару замечаний
Привет, всё поправил

2023-11-15 19:36 UTC, closed without merging