Flow домашняя работа
Otus-Android/HomeWork_03 pull request #148
Opened 2023-11-23 06:56 UTC by Alienstemple

В пункте 1 края исправляется с помощью postValue вместо setValue

2023-11-30 14:43 UTC, antonkazakov requested changes
Привет. оставил пару замечаний

2023-11-30 14:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Нужно убрать. Коллектор на main оставим, если нужно диспатчер переключить то flowOn

2023-11-30 14:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Result<Fact>?>(null)
Можно добавить еще один наследник Result, например, Initial, тогда не придется nullable его делать

2023-11-30 14:43 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                0 -> emit("$number")
emit("$number") можно вынести за when блок

2023-12-23 17:07 UTC, Alienstemple commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Готово, спасибо. Теперь с  flowOn работает на дефолтном диспетчере, но, что интересно, если оставить flow репозитория на main треде даже с большим delay не возникает ошибки.

2023-12-23 17:07 UTC, Alienstemple commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Result<Fact>?>(null)
Так правда удобнее, спасибо!

2023-12-23 17:07 UTC, Alienstemple commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                0 -> emit("$number")
Готово

2023-12-24 17:38 UTC, closed without merging