Flow homework
Otus-Android/HomeWork_03 pull request #157
Opened 2024-01-23 12:53 UTC by 1slash77

2024-01-31 17:43 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-01-31 17:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    // либо какой-то факт нужно в коде задать сразу.
Я бы тут сделал какой то наследник Result, например Initial/Loading, ведь наверняка в реальном приложении у тебя будет какая то начальная загрузка или скелетоны

2024-01-31 17:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
В отэто нужно убрать и переключить диспатчер на котором мы эмитим элементы через оператор

2024-02-01 16:29 UTC, 1slash77 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    // либо какой-то факт нужно в коде задать сразу.
поправил

2024-02-01 18:14 UTC, 1slash77 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Я честно говоря, вообще не понял, что ты имеешь ввиду... Можешь пояснить?

2024-02-01 18:55 UTC, 1slash77 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Поправил

2024-02-10 18:11 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Именно это и имел ввиду)

2024-02-10 18:11 UTC, closed without merging