Done
Otus-Android/HomeWork_03 pull request #159
Opened 2024-01-27 12:45 UTC by StanislavRepinskas

2024-02-10 17:50 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-02-10 17:50 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                throw RuntimeException("Test error")
А это зачем в пулл реквесте?)

2024-02-10 17:50 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    withContext(Dispatchers.Main) {
Чтобы тут не переключать диспатчер, нужно убрать withContext(Dispatchers.IO). 
Нужно коллектить на Main, а эмитить на IO

2024-02-10 17:50 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Result?>(null)
Можно добавить еще один наследник Result, тогда не придется с null работать

2024-02-10 17:50 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                emit(it.toString())
emit(it.toString()) можно вынести за if блок, а еще можно чуть компактнее сделать использовав when

2024-02-11 10:14 UTC, StanislavRepinskas commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +                throw RuntimeException("Test error")
для себя, наглядный пример, можно запустить посмотреть потом когда нибудь) Могу убрать если очень надо

2024-02-11 10:27 UTC, StanislavRepinskas commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    withContext(Dispatchers.Main) {
Да, и правда переключения там лишние, он и так будет на мейн после возврата из вызова ретрофит.
Не понял зачем нам делать emit(latestNews) на io.

2024-02-11 10:29 UTC, StanislavRepinskas commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Result?>(null)
Добавил.

2024-02-11 10:33 UTC, StanislavRepinskas commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                emit(it.toString())
вынес

2024-02-11 13:49 UTC, closed without merging