Flow homework
Otus-Android/HomeWork_03 pull request #165
Opened 2024-02-11 19:54 UTC by LexAndro3723

Flow homework

2024-02-18 09:44 UTC, antonkazakov requested changes
Привет. Оставил несколько комментариев

2024-02-18 09:44 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(Dispatchers.Main) {
Внутри viewModelScope уже Dispatchers.Main.immediate используется, можно убрать withContext

2024-02-18 09:44 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    catsRepository.listenForCatFacts().collect {
А зачем 2 подписки на репозиторий?

2024-02-18 09:44 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            }.collect {
А зачем тут коллект?

2024-03-05 11:00 UTC, LexAndro3723 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +            withContext(Dispatchers.Main) {
Исправил

2024-03-05 11:00 UTC, LexAndro3723 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    catsRepository.listenForCatFacts().collect {
Исправил

2024-03-05 11:00 UTC, LexAndro3723 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +            }.collect {
Исправил

2024-03-12 10:05 UTC, closed without merging

2024-03-12 10:05 UTC, antonkazakov commented
👍