HW3 задачи разбил на комиты
Otus-Android/HomeWork_03 pull request #174
Opened 2024-04-19 21:43 UTC by EdKrupenin

2024-05-02 08:50 UTC, antonkazakov requested changes
Привет. Оставил коммент

2024-05-02 08:50 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно убрать. Здесь же лучше коллектить на main, а эмитить в рамках задания на io

2024-05-05 09:20 UTC, antonkazakov reviewed
👍

2024-05-05 09:20 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    .flowOn(Dispatchers.IO)
Некритично но я бы это в репозиторий перенес переключение, чтобы потенциальные другие потребители этого метода могли спокойно жить и не переключать

2024-05-05 09:20 UTC, closed without merging

2024-05-06 15:50 UTC, EdKrupenin commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +                    .flowOn(Dispatchers.IO)
Оки, учту этот подход и исправлю на днях