ДЗ "Flow": Роман Скаскевич
Otus-Android/HomeWork_03 pull request #192
Opened 2024-09-08 22:07 UTC by romasks

2024-09-26 12:06 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-09-26 12:06 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно убрать, эмиттер переключать через оператор, а для коллектора, кажется, диспатчер из viewModelScope отлично подойдет

2024-09-26 12:06 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsSharedFlow = MutableSharedFlow<Fact>()
Я думаю тебе нужно один флоу сделать, а вот RESULT его упаковку и распаковку перенести

2024-10-28 23:52 UTC, romasks commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Немного с опозданием, но всё-таки спрошу: какой оператор для эмиттера имеется в виду?

2024-10-29 00:00 UTC, romasks commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsSharedFlow = MutableSharedFlow<Fact>()
@antonkazakov  Немного не понял про перенос RESULT - имеется в виду передать распаковку на ответственность в Activity?

2024-11-23 09:37 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
привет) flowOn

2024-11-23 09:38 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsSharedFlow = MutableSharedFlow<Fact>()
Ну обычно так делают, да, тоесть этот Result по сути ViewState

2025-11-17 13:35 UTC, closed without merging