HW3_by_Khubulov_George
Otus-Android/HomeWork_03 pull request #196
Opened 2024-10-21 20:36 UTC by GeorgeBozon

2024-11-04 17:12 UTC, antonkazakov requested changes
Привет. Оставил комменты

2024-11-04 17:12 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно убрать, поменять диспатчер эмиттера через оператор

2024-11-04 17:12 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$currentInt")
Можно вынести из if

2024-11-07 18:41 UTC, GeorgeBozon commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$currentInt")
поправил в 4 коммите

2024-11-07 18:41 UTC, GeorgeBozon commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
поправил в 4 коммите

2024-11-23 08:31 UTC, closed without merging