[ДЗ | Flow]
Otus-Android/HomeWork_03 pull request #197
Opened 2024-10-24 18:49 UTC by jeghor

2024-11-04 17:19 UTC, antonkazakov requested changes
Оставил комментарии

2024-11-04 17:19 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsService.kt
> +    suspend fun getCatFact(): Response<Fact>
Тут тоже проще будет убрать Response

2024-11-04 17:19 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Fact?>(null)
Лучше сделать один флоу

2024-11-04 17:19 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Нужно убрать, переключить диспатчер через оператор

2024-11-19 19:32 UTC, jeghor commented on flowcats/src/main/java/otus/homework/flowcats/CatsService.kt
> +    suspend fun getCatFact(): Response<Fact>
Тоже, что и в pr по корутинам писал) Если нужно, переделаю

2024-11-19 19:34 UTC, jeghor commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +    private val _catsFlow = MutableStateFlow<Fact?>(null)
Я так сделал, потому что не хочу, чтобы в активити обрабатывался как то результат, а просто чтобы ui обновлялся

2024-11-23 08:34 UTC, closed without merging