FlowHomework: Виталий Чупин
Otus-Android/HomeWork_03 pull request #198
Opened 2024-10-27 12:43 UTC by vitalik123123

2024-11-04 17:22 UTC, antonkazakov requested changes
Оставил комментарии

2024-11-04 17:22 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
нужно убрать и эмиттер переключать через оператор

2024-11-04 17:22 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$it")
Можно вынести за when

2024-11-07 14:34 UTC, vitalik123123 commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit("$it")
исправил

2024-11-23 10:22 UTC, closed without merging