Flow Homework from Pavel Scherbakov
Otus-Android/HomeWork_03 pull request #71
Opened 2022-07-16 07:37 UTC by PavelScherbakov

2022-07-31 08:30 UTC, antonkazakov requested changes
Привет. А где 2 и 3 задания? Если есть вопросы, напиши пожалуйста мне в Телеграме

2022-07-31 08:30 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно брать. Мы же хотим на UI треде _uiState.emit(Success(it)) вызывать. Переключи диспатчер в catsRepository

2022-08-02 06:58 UTC, PavelScherbakov commented
Flow Homework состоит из двух задач (https://kazakovanton.notion.site/Flow-Homework-c8ddbb354f56428c829aad1056b4a2f0), тут два коммита по каждой задаче. А где 3 задача?

2022-08-13 14:18 UTC, antonkazakov reviewed
👍

2022-08-13 14:18 UTC, closed without merging