3й пункт добавил
Otus-Android/HomeWork_03 pull request #75
Opened 2022-07-26 09:13 UTC by stupkalex

2022-08-14 09:34 UTC, antonkazakov requested changes

2022-08-14 09:34 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +    private val coroutineScope = CoroutineScope(Dispatchers.IO)
Так, а зачем эта переменная? :)

2022-08-14 09:34 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +        return flow {
Сделай, пожалуйста, так чтобы эмиты происходили на IO диспатчере

2022-08-14 09:34 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +    private val coroutineScope = CoroutineScope(Dispatchers.IO)
Почему тут IO? 
Советую тут использовать `lifecycleScope` из **activity-ktx**

2022-08-14 09:34 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/Result.kt
> +sealed class Result {
Можно сделать `sealed interface`

2022-08-14 09:34 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/Result.kt
> +sealed class Result {
Добавь дженерик, получится более универсальный класс

2022-08-14 09:34 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/Result.kt
> +
Отформатируй этот файл

2022-08-14 09:34 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                    if (it % 3 == 0) {
Почему этот if внутри else? Мне кажется гораздо лучше будет если переписать на when

2022-08-14 09:34 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit(it.toString())
Этот эмит дублируется во всех ветках, вынеси чтобы не дублировать

2022-08-14 09:34 UTC, antonkazakov commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +        return  flow {
`dotsRepository.completed()` вызывается не при любом исходе. 
Перепиши на `doOnCompletion`

2022-08-17 16:03 UTC, stupkalex commented on flowcats/src/main/java/otus/homework/flowcats/Result.kt
> +sealed class Result {
Не разобрался как(

2022-08-17 16:04 UTC, stupkalex commented on flowcats/src/main/java/otus/homework/flowcats/Result.kt
> +sealed class Result {
Пытался и не вышло, буду признателен если покажете пример

2022-08-17 16:16 UTC, stupkalex commented on operators/src/main/java/otus/homework/flow/SampleInteractor.kt
> +                        emit(it.toString())
Когда выношу emit  ( emit (when...{...}) он эмитит только одно значение, а зачастую нужно 2 (чисто и string)

2023-11-09 09:36 UTC, closed without merging