Sementsov FlowHomeWork
Otus-Android/HomeWork_03 pull request #78
Opened 2022-08-13 11:06 UTC by DeveloperSementsov

FlowHomeWork

2022-09-03 12:43 UTC, antonkazakov requested changes
Привет. Поправь пожалуйста замечания

2022-09-03 12:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +        return CoroutineExceptionHandler { _, throwable ->
Аналогично с ДЗ по корутинам, ожидаемые исключения давай хендлить через try/catch или в декларативной форме через `catch` оператор на флоу

2022-09-03 12:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Тебе же не нужно ловить события на IO диспатчере. Сделай так чтобы эмиттер работал на IO, а коллектор на Main

2022-09-03 12:43 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/ViewModelExtensions.kt
> +fun <T> Flow<T>.launchWhenStarted(lifecycleScope: LifecycleCoroutineScope) {
А какой смысл у этой функции? Почему нельзя просто использовать `launchWhenStarted`

2022-11-28 20:50 UTC, DeveloperSementsov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
> +        return CoroutineExceptionHandler { _, throwable ->
done

2022-11-28 20:55 UTC, DeveloperSementsov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
done

2022-11-28 21:03 UTC, DeveloperSementsov commented on flowcats/src/main/java/otus/homework/flowcats/ViewModelExtensions.kt
> +fun <T> Flow<T>.launchWhenStarted(lifecycleScope: LifecycleCoroutineScope) {
Брал из своего проекта, точно не знаю смысл, но уточню :) Здесь убрал.

2022-12-11 14:39 UTC, antonkazakov commented
👍

2022-12-11 14:39 UTC, closed without merging