Ульянов А.Г. ДЗ по flow
Otus-Android/HomeWork_03 pull request #89
Opened 2022-10-23 11:53 UTC by schnaps1981

2022-11-06 17:15 UTC, antonkazakov requested changes

2022-11-06 17:15 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        scope.cancel()
У тебя здесь должно упасть приложение т.к. в скоуп ты не прокинул инстанс job

2022-11-06 17:15 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        scope.cancel()
Кстати можешь взять https://developer.android.com/topic/libraries/architecture/coroutines#lifecyclescope

2022-11-06 17:15 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +            val latestNews = try {
Мне кажется правильнее try перенести в viewmodel

2022-11-06 17:15 UTC, antonkazakov commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
Это нужно убрать, мы хотим коллектить на главном потоке, а эмитить на IO.

2022-11-14 17:44 UTC, schnaps1981 commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        scope.cancel()
здесь job не требуется, здесь активити уничтожается, и вместе с ней отменяются все дети в скоупе. скоуп можно спокойно отменяь, так как он точно никогда больше не будет запущен (cancel вызывается в onDestroy).

Про lifecycleScope я знаю, спасибо, но в этой задаче этого не требовалось. Хотя свой скоуп создавать не требовалось тоже ))))

2022-11-14 17:45 UTC, schnaps1981 commented on flowcats/src/main/java/otus/homework/flowcats/MainActivity.kt
> +        scope.cancel()
в общем вставил lifecycleScope ))))

2022-11-14 17:47 UTC, schnaps1981 commented on flowcats/src/main/java/otus/homework/flowcats/CatsRepository.kt
> +            val latestNews = try {
может быть, но я исходил из того, что latestNews это поток данных, который содержит Result, но Result это в том числе и ошибки тоже.

2022-11-14 18:00 UTC, schnaps1981 commented on flowcats/src/main/java/otus/homework/flowcats/CatsViewModel.kt
>              withContext(Dispatchers.IO) {
да, преписал.
1. изменил эндпоинт API (так как тот ,что в задании не рабочий), изменил модели ответа
2. вью-модель теперь просто как прокси для передачи флоу из репозитория в активити
3. коллект флоу происходит теперь в активити

2022-11-26 12:54 UTC, antonkazakov commented
👍

2022-11-26 12:54 UTC, closed without merging